### ISSUE TITLE
Colaboración en el proyecto

### ISSUE THREAD

**Issue by fabibeto** [martinch12/devtech-podcast-web#5]
Hola Ernesto !!! como estas ? espero que bien.

Te comento que voy a colaborar en el proyecto podcast DevTech, estoy atento a tus sugerencias, gracias.

Saludos !!!
Fabián

**Comment by martinch12** [comment]
Hola! perfecto!! cuando termines de editar tu tarjeta realiza el pullrequest! Lo voy a estar esperando! Saludos!😉
